In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("../data/processed/uci_household_5min.csv", index_col="datetime", parse_dates=True)

print(df.shape)
df.head()

(415053, 7)

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
datetime,,,,,,,
2006-12-16 17:20:00,4.2160,0.4180,234.840,18.40,0.0,1.0,17.0
2006-12-16 17:25:00,4.6616,0.4972,234.272,19.96,0.0,1.4,16.8
2006-12-16 17:30:00,3.8360,0.5116,234.204,16.56,0.0,1.2,16.8
2006-12-16 17:35:00,4.6684,0.4100,234.212,20.00,0.0,1.0,16.8
2006-12-16 17:40:00,3.9176,0.0616,235.890,16.76,0.0,0.0,17.0

In [2]:
target_col = "Global_active_power"

for lag in [1, 2, 3, 6, 12]:
    df[f"{target_col}_lag_{lag}"] = df[target_col].shift(lag)

df.head(15)

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3,Global_active_power_lag_1,Global_active_power_lag_2,Global_active_power_lag_3,Global_active_power_lag_6,Global_active_power_lag_12
datetime,,,,,,,,,,,,
2006-12-16 17:20:00,4.2160,0.4180,234.840,18.40,0.0,1.0,17.0,NaN,NaN,NaN,NaN,NaN
2006-12-16 17:25:00,4.6616,0.4972,234.272,19.96,0.0,1.4,16.8,4.2160,NaN,NaN,NaN,NaN
2006-12-16 17:30:00,3.8360,0.5116,234.204,16.56,0.0,1.2,16.8,4.6616,4.2160,NaN,NaN,NaN
2006-12-16 17:35:00,4.6684,0.4100,234.212,20.00,0.0,1.0,16.8,3.8360,4.6616,4.2160,NaN,NaN
2006-12-16 17:40:00,3.9176,0.0616,235.890,16.76,0.0,0.0,17.0,4.6684,3.8360,4.6616,NaN,NaN
2006-12-16 17:45:00,5.5256,0.0000,233.800,23.76,0.0,0.0,16.8,3.9176,4.6684,3.8360,NaN,NaN
2006-12-16 17:50:00,3.1240,0.0000,235.454,13.20,0.0,0.0,17.0,5.5256,3.9176,4.6684,4.2160,NaN
2006-12-16 17:55:00,3.8284,0.0848,234.636,16.40,0.0,0.0,16.8,3.1240,5.5256,3.9176,4.6616,NaN
2006-12-16 18:00:00,3.3708,0.1504,237.188,14.36,0.0,10.6,17.2,3.8284,3.1240,5.5256,3.8360,NaN
2006-12-16 18:05:00,6.0100,0.1548,232.762,25.80,0.0,36.6,16.6,3.3708,3.8284,3.1240,4.6684,NaN
2006-12-16 18:10:00,2.9824,0.1524,236.748,12.96,0.0,12.6,17.2,6.0100,3.3708,3.8284,3.9176,NaN
2006-12-16 18:15:00,4.1296,0.0516,234.332,18.00,0.0,6.4,16.8,2.9824,6.0100,3.3708,5.5256,NaN
2006-12-16 18:20:00,3.0360,0.0000,235.536,12.96,0.0,1.2,17.0,4.1296,2.9824,6.0100,3.1240,4.2160
2006-12-16 18:25:00,4.1400,0.0000,234.542,17.72,0.0,1.0,17.0,3.0360,4.1296,2.9824,3.8284,4.6616
2006-12-16 18:30:00,2.9404,0.0700,235.190,12.60,0.0,0.8,16.8,4.1400,3.0360,4.1296,3.3708,3.8360

In [3]:
for window in [3, 6, 12]:
    df[f"{target_col}_roll_mean_{window}"] = df[target_col].shift(1).rolling(window).mean()
    df[f"{target_col}_roll_std_{window}"] = df[target_col].shift(1).rolling(window).std()

df.head(15)

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3,Global_active_power_lag_1,Global_active_power_lag_2,Global_active_power_lag_3,Global_active_power_lag_6,Global_active_power_lag_12,Global_active_power_roll_mean_3,Global_active_power_roll_std_3,Global_active_power_roll_mean_6,Global_active_power_roll_std_6,Global_active_power_roll_mean_12,Global_active_power_roll_std_12
datetime,,,,,,,,,,,,,,,,,,
2006-12-16 17:20:00,4.2160,0.4180,234.840,18.40,0.0,1.0,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-12-16 17:25:00,4.6616,0.4972,234.272,19.96,0.0,1.4,16.8,4.2160,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-12-16 17:30:00,3.8360,0.5116,234.204,16.56,0.0,1.2,16.8,4.6616,4.2160,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-12-16 17:35:00,4.6684,0.4100,234.212,20.00,0.0,1.0,16.8,3.8360,4.6616,4.2160,NaN,NaN,4.237867,0.413234,NaN,NaN,NaN,NaN
2006-12-16 17:40:00,3.9176,0.0616,235.890,16.76,0.0,0.0,17.0,4.6684,3.8360,4.6616,NaN,NaN,4.388667,0.478635,NaN,NaN,NaN,NaN
2006-12-16 17:45:00,5.5256,0.0000,233.800,23.76,0.0,0.0,16.8,3.9176,4.6684,3.8360,NaN,NaN,4.140667,0.458848,NaN,NaN,NaN,NaN
2006-12-16 17:50:00,3.1240,0.0000,235.454,13.20,0.0,0.0,17.0,5.5256,3.9176,4.6684,4.2160,NaN,4.703867,0.804586,4.470867,0.626415,NaN,NaN
2006-12-16 17:55:00,3.8284,0.0848,234.636,16.40,0.0,0.0,16.8,3.1240,5.5256,3.9176,4.6616,NaN,4.189067,1.223598,4.288867,0.838132,NaN,NaN
2006-12-16 18:00:00,3.3708,0.1504,237.188,14.36,0.0,10.6,17.2,3.8284,3.1240,5.5256,3.8360,NaN,4.159333,1.234528,4.150000,0.833033,NaN,NaN
2006-12-16 18:05:00,6.0100,0.1548,232.762,25.80,0.0,36.6,16.6,3.3708,3.8284,3.1240,4.6684,NaN,3.441067,0.357418,4.072467,0.887943,NaN,NaN
2006-12-16 18:10:00,2.9824,0.1524,236.748,12.96,0.0,12.6,17.2,6.0100,3.3708,3.8284,3.9176,NaN,4.403067,1.410328,4.296067,1.186687,NaN,NaN
2006-12-16 18:15:00,4.1296,0.0516,234.332,18.00,0.0,6.4,16.8,2.9824,6.0100,3.3708,5.5256,NaN,4.121067,1.647351,4.140200,1.302140,NaN,NaN
2006-12-16 18:20:00,3.0360,0.0000,235.536,12.96,0.0,1.2,17.0,4.1296,2.9824,6.0100,3.1240,4.2160,4.374000,1.528525,3.907533,1.116586,4.189200,0.911933
2006-12-16 18:25:00,4.1400,0.0000,234.542,17.72,0.0,1.0,17.0,3.0360,4.1296,2.9824,3.8284,4.6616,3.382667,0.647418,3.892867,1.129440,4.090867,0.970518
2006-12-16 18:30:00,2.9404,0.0700,235.190,12.60,0.0,0.8,16.8,4.1400,3.0360,4.1296,3.3708,3.8360,3.768533,0.634414,3.944800,1.133041,4.047400,0.954175

In [4]:
df["hour"] = df.index.hour
df["day_of_week"] = df.index.dayofweek
df["is_weekend"] = (df["day_of_week"] >= 5).astype(int)

df["hour_sin"] = np.sin(2 * np.pi * df["hour"] / 24)
df["hour_cos"] = np.cos(2 * np.pi * df["hour"] / 24)

df[["hour", "day_of_week", "is_weekend", "hour_sin", "hour_cos"]].head(10)

                     hour  day_of_week  is_weekend  hour_sin      hour_cos
datetime
2006-12-16 17:20:00    17            5           1 -0.965926 -2.588190e-01
2006-12-16 17:25:00    17            5           1 -0.965926 -2.588190e-01
2006-12-16 17:30:00    17            5           1 -0.965926 -2.588190e-01
2006-12-16 17:35:00    17            5           1 -0.965926 -2.588190e-01
2006-12-16 17:40:00    17            5           1 -0.965926 -2.588190e-01
2006-12-16 17:45:00    17            5           1 -0.965926 -2.588190e-01
2006-12-16 17:50:00    17            5           1 -0.965926 -2.588190e-01
2006-12-16 17:55:00    17            5           1 -0.965926 -2.588190e-01
2006-12-16 18:00:00    18            5           1 -1.000000 -1.836970e-16
2006-12-16 18:05:00    18            5           1 -1.000000 -1.836970e-16

In [5]:
before_rows = len(df)
df = df.dropna()
after_rows = len(df)

print(f"Rows before: {before_rows}")
print(f"Rows dropped: {before_rows - after_rows}")
print(f"Rows remaining: {after_rows}")

Rows before: 415053
Rows dropped: 12
Rows remaining: 415041

In [6]:
df["target_5min"] = df[target_col].shift(-1)
df["target_15min"] = df[target_col].shift(-3)
df["target_30min"] = df[target_col].shift(-6)

df = df.dropna()

df[[target_col, "target_5min", "target_15min", "target_30min"]].head(10)

,Global_active_power,target_5min,target_15min,target_30min
datetime,,,,
2006-12-16 18:20:00,3.0360,4.1400,4.0508,2.7800
2006-12-16 18:25:00,4.1400,2.9404,2.3916,4.1652
2006-12-16 18:30:00,2.9404,4.0508,3.5896,3.5880
2006-12-16 18:35:00,4.0508,2.3916,2.7800,3.4544
2006-12-16 18:40:00,2.3916,3.5896,4.1652,3.4112
2006-12-16 18:45:00,3.5896,2.7800,3.5880,3.4064
2006-12-16 18:50:00,2.7800,4.1652,3.4544,3.3332
2006-12-16 18:55:00,4.1652,3.5880,3.4112,3.5932
2006-12-16 19:00:00,3.5880,3.4544,3.4064,3.3760
2006-12-16 19:05:00,3.4544,3.4112,3.3332,3.3512

In [7]:
n = len(df)
train_end = int(n * 0.65)
val_end = int(n * 0.80)

train_df = df.iloc[:train_end]
val_df = df.iloc[train_end:val_end]
test_df = df.iloc[val_end:]

print(f"Train: {len(train_df)} rows ({train_df.index.min()} to {train_df.index.max()})")
print(f"Val:   {len(val_df)} rows ({val_df.index.min()} to {val_df.index.max()})")
print(f"Test:  {len(test_df)} rows ({test_df.index.min()} to {test_df.index.max()})")

Train: 269772 rows (2006-12-16 18:20:00 to 2009-07-10 11:15:00)
Val:   62256 rows (2009-07-10 11:20:00 to 2010-02-11 15:15:00)
Test:  83007 rows (2010-02-11 15:20:00 to 2010-11-26 20:30:00)

In [8]:
train_df.to_csv("../data/processed/train_uci_household.csv")
val_df.to_csv("../data/processed/val_uci_household.csv")
test_df.to_csv("../data/processed/test_uci_household.csv")

print("Saved train/val/test splits to data/processed/")
print(f"Feature columns: {list(df.columns)}")

Saved train/val/test splits to data/processed/
Feature columns: ['Global_active_power', 'Global_reactive_power', 'Voltage', 'Global_intensity', 'Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3', 'Global_active_power_lag_1', 'Global_active_power_lag_2', 'Global_active_power_lag_3', 'Global_active_power_lag_6', 'Global_active_power_lag_12', 'Global_active_power_roll_mean_3', 'Global_active_power_roll_std_3', 'Global_active_power_roll_mean_6', 'Global_active_power_roll_std_6', 'Global_active_power_roll_mean_12', 'Global_active_power_roll_std_12', 'hour', 'day_of_week', 'is_weekend', 'hour_sin', 'hour_cos', 'target_5min', 'target_15min', 'target_30min']